/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // DevLens Nordic Theme Color Schemes
        surface: "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#44474d",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        outline: "#75777d",
        "outline-variant": "#c4c6cd",
        "surface-tint": "#505f78",
        primary: "#05162b",
        "on-primary": "#ffffff",
        "primary-container": "#1b2b41",
        "on-primary-container": "#8292ad",
        "inverse-primary": "#b7c7e4",
        secondary: "#006b5f",
        "on-secondary": "#ffffff",
        "secondary-container": "#62fae3",
        "on-secondary-container": "#007165",
        tertiary: "#1b004f",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#31077f",
        "on-tertiary-container": "#9b80ee",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d4e3ff",
        "primary-fixed-dim": "#b7c7e4",
        "on-primary-fixed": "#0b1c31",
        "on-primary-fixed-variant": "#38485f",
        "secondary-fixed": "#62fae3",
        "secondary-fixed-dim": "#3cddc7",
        "on-secondary-fixed": "#00201c",
        "on-secondary-fixed-variant": "#005047",
        "tertiary-fixed": "#e8ddff",
        "tertiary-fixed-dim": "#cebdff",
        "on-tertiary-fixed": "#21005e",
        "on-tertiary-fixed-variant": "#4f319c",
        background: "#f8f9ff",
        "on-background": "#0b1c30",
        "surface-variant": "#d3e4fe",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
}
